logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  servlet:
    encoding:
      force: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mohang
    url: jdbc:mysql://localhost:3306/mohang?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: mohang
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        format_sql: true
        show_sql: true
    database: mysql
  session:
    store-type: jdbc
  sql:
    init:
      mode: always
  data.rest:
    base-path: /hangapi
    detection-strategy: annotated
